#!/bin/bash

# Enable ubuntu dark mode
gsettings set org.gnome.desktop.interface gtk-theme Yaru-dark
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
gsettings reset org.gnome.shell.ubuntu color-scheme

# Caps is now another Ctrl
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier']"
# To disable
# gsettings set org.gnome.desktop.input-sources xkb-options "[]"


read -p "Generate new ssh key? (Y/n)" -n 1 -r
echo    
if [[ $REPLY =~ ^[Y]$ ]]
then
	echo "git email account : "
	read gitEmail
	ssh-keygen -t ed25519 -C ${gitEmail}
fi
