"----GLOBAL SETTINGS----"

" Use Vim settings rather than Vi settings
set nocompatible


"----GENERAL CONFIGURATION OPTIONS----" 

" Allow backspacing over indention, line breaks and insertions start
set backspace=eol,indent,start

" Allow bigger history of excuted commands
set history=1000

" Set bigger history of executed commands
set showcmd

" Show current mode
set showmode

" Minimal amount of line under and above the cursor
set scrolloff=5

" Show current line number
set number

" Hide buffers instead of closing them
set hidden
" Color scheme
colorscheme jellybeans

" Highlight cursor line
set cursorline

" Line numbers
set nu

" Enable syntax highlighting
syntax on

" Use colors that suit a dark background
set background=dark

" Set the window title, reflecting the file currently being edited
set title

" Mouse mode activated
set mouse=a


"----SWAP AND BACKUP FILE OPTIONS----"

set noswapfile
set nobackup
set nowb

"----INDENTATIONS OPTIONS----"

" New line inherit the indentation of previous lines
set autoindent

" Show existing tab with 4 (default value 8) spaces width
set tabstop=4

" Don't wrap lines
set nowrap

"----SEARCH OPTIONS----"

" Find the next match as we type the search
set incsearch

" Highlight searches by default
set hlsearch

" Ignore case when searching...
set ignorecase

" ...unless you type a capital
set smartcase

" Double esc auto turn off hlsearch when research is ended
nnoremap <esc><esc> :silent! nohls<cr>


"----TEXT RENDERING OPTIONS----"

" Use an encoding that supports Unicode
set encoding=utf-8


"----STATUS LINE----"

" Always display status line
set laststatus=2

" Custom status line
set statusline=%f\ %l\|%c\ %m%=%p%%\ (%Y%R)


" Directory listing style
let g:netrw_liststyle = 3

" Default window for netrw window 
let g:netrw_browse_split = 4
