NAME := a.out

CC := c++
CFLAGS := -Wall -Werror -Wextra -std=c++98 -I include/

SRCDIR := src/
OBJSDIR := objs/

SRC := main.cpp

OBJS := $(SRC:%.cpp=$(OBJSDIR)%.o)

all:
	make $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@

$(OBJSDIR)%.o: $(SRCDIR)%.cpp
	mkdir -p $(OBJSDIR)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJSDIR) 

fclean: clean
	rm -rf $(NAME)

re: fclean
	make $(NAME)

.PHONY: all clean re fclean
