#include "x.hpp"

x::x(void)
{
	std::cout << "x default constructor called." << std::endl;

	return ;
}

x::~x(void)
{
	std::cout << "x destructor called" << std::endl;

	return ;
}

x::x(x const &src)
{
	std::cout << "x copy constructor called" << std::endl;
	*this = src;

	return ;
}

x &x::operator=(x const &rhs)
{
	std::cout << "x copy assignment operator called" << std::endl;

	return (*this);
}
